#!/opt/bin/php
<?php declare(strict_types=1);

use App\Console\Kernel;
use Illuminate\Contracts\Console\Kernel as BaseKernel;
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$appRoot = getenv('LAMBDA_TASK_ROOT');
require_once $appRoot . '/vendor/autoload.php';
require_once $appRoot . '/bootstrap/app.php';

/** @var Kernel $kernel */
$kernel = app(BaseKernel::class);
$kernel->bootstrap();

$status = $kernel->handle(
    $input = new StringInput(getenv('ARTISAN_COMMAND')),
    new ConsoleOutput
);

$kernel->terminate($input, $status);
